print("Welcome to my first project in python:)")
print("Band name generator")
print()
question1 = input("Write some nice color\n")
print()
question2 = input("Write some adjective\n")
print()
question3 = input("What kind of animal do you like?\n")
print()
q1 = question1.upper()
q2 = question2.upper()
q3 = question3.upper()
print("The best name of you band is:" + "   " + q1 + " " + q2 + " " + q3 + " " + ":)")